env:
  "vue/setup-compiler-macros": true

parserOptions:
  parser: "@typescript-eslint/parser"

rules:
  no-unused-vars: off
  vue/first-attribute-linebreak: off

extends:
  - "eslint:recommended"
  - "plugin:vue/vue3-recommended"
  - "prettier"
